# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnraidTui < Formula
  desc "Terminal UI for monitoring and managing Unraid servers"
  homepage "https://github.com/Greite/unraid-tui"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Greite/unraid-tui/releases/download/v0.7.0/unraid-tui_0.7.0_darwin_amd64.tar.gz"
      sha256 "3c2ec29ac871d971997455ee6f6c7b25b3e8639a04e2bc39cf9290e7b2901740"

      define_method(:install) do
        bin.install "unraid-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Greite/unraid-tui/releases/download/v0.7.0/unraid-tui_0.7.0_darwin_arm64.tar.gz"
      sha256 "d63e71f7b6173e7d2794bd1bc6f8cb8b883a9059f6d53b44366ec722a9f6fb3d"

      define_method(:install) do
        bin.install "unraid-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Greite/unraid-tui/releases/download/v0.7.0/unraid-tui_0.7.0_linux_amd64.tar.gz"
      sha256 "e2d1c4b8b0fd4d9eb084069ee2ebe7ae2bbae8942b32650c9840e404ac6ac53e"
      define_method(:install) do
        bin.install "unraid-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Greite/unraid-tui/releases/download/v0.7.0/unraid-tui_0.7.0_linux_arm64.tar.gz"
      sha256 "f7a2c89e0a0b360085a5f19fe60517349f88cbf2df1cd5ef9da8a7ba81fe3127"
      define_method(:install) do
        bin.install "unraid-tui"
      end
    end
  end

  test do
    system bin/"unraid-tui", "--help"
  end
end
