# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnraidTui < Formula
  desc "Terminal UI for monitoring and managing Unraid servers"
  homepage "https://github.com/Greite/unraid-tui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Greite/unraid-tui/releases/download/v0.1.0/unraid-tui_0.1.0_darwin_amd64.tar.gz"
      sha256 "096ebfdff9988c6e43247c4fd8b05768a914dbde39034c4da8374213a105aacc"

      define_method(:install) do
        bin.install "unraid-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Greite/unraid-tui/releases/download/v0.1.0/unraid-tui_0.1.0_darwin_arm64.tar.gz"
      sha256 "3d288e8612b65696676ad6c5637e079751e5a39bd41692255cbb3593c2660da4"

      define_method(:install) do
        bin.install "unraid-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Greite/unraid-tui/releases/download/v0.1.0/unraid-tui_0.1.0_linux_amd64.tar.gz"
      sha256 "0c06ffe2d2d97a3b94fae3d03b218b6892ab7dea91b0201537c19783f0ba5e9c"
      define_method(:install) do
        bin.install "unraid-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Greite/unraid-tui/releases/download/v0.1.0/unraid-tui_0.1.0_linux_arm64.tar.gz"
      sha256 "f0bbcb9ff39756f20df4641e71c859633862df2f78ecb92b638c2b15a865baac"
      define_method(:install) do
        bin.install "unraid-tui"
      end
    end
  end

  test do
    system bin/"unraid-tui", "--help"
  end
end
